### ISSUE TITLE
Nuovi contagiati sono in realtà Attualmente positivi

### ISSUE THREAD

**Issue by riodda** [LucaAngioloni/fit-COVID19#1]
Buongiorno, grazie per il tuo lavoro e interessante visualizzazione. Credo dai numeri che il grafico Nuovi contagiati sia in realtà gli attualmente positivi.
Grazie e stiamo a casa.

**Comment by LucaAngioloni** [comment]
Buonasera,
Grazie mille per la segnalazione. Avevo frainteso il significato della colonna nel file fornito dalla protezione civile. Il grafico mostra infatti la colonna `nuovi_attualmente_positivi`.

Provvederò in serata ad aggiustare il codice ed eventualmente a fornire entrambi i grafici.
Saluti.

**Comment by LucaAngioloni** [comment]
Adesso il grafico mostra i dati corretti.
L'app web si aggiornerà automaticamente tra poco.
Grazie ancora.

**Comment by davscheno** [comment]
credo fosse giusto in precedenza perché calcolando i nuovi contagiati,  prendendo il totale del giorno e sottraendo il totale del giorno precedente , si tiene conto anche dei decessi e delle guarigioni, infatti dai dati di oggi: (19.03.20)  nuovi_attualmente_positivi= 4480 + dimessi 415 + deceduti 427 = 5322 che è appunto la differenza dei totali di ieri e oggi, in quanto quello è un dato cumulativo che tiene conto di tutti e tre gli stati.

**Comment by LucaAngioloni** [comment]
Quello che però è di interesse prevedere è se e quando i nuovi contagi finiranno ed il loro andamento.

`nuovi_attualmente_positivi` potrebbe risultare nullo in caso ci siano ad esempio 100 contagi, 50 morti e 50 guariti. Però è importante notare che ci sono stati 100 contagi nella giornata.

L'epidemia termina quando non ci sono più nuovi contagi.

**Comment by davscheno** [comment]
Sicuro ? Penso che in un caso del genere facendo la sottrazione dal totali si avrebbe 200 casi per cui diminuendo di guariti e decessi ecco 100 positivi. 

Davide Schenone

**Comment by LucaAngioloni** [comment]
Le persone che guariscono o muoiono oggi non hanno contratto il virus oggi, ma diversi giorni prima. 
Quello che interessa per i nuovi contagi sono solo i nuovi contagi, ovvero persone il cui tampone risulta positivo oggi.

Quando non ci sono più tamponi positivi, sono finiti i contagi. 
Allo stesso tempo ovviamente ci saranno ancora delle persone positive che possono sperabilmente guarire o nel peggiore dei casi morire. Questi non sono però "nuovi".
