### ISSUE TITLE
nuovi contagi

### ISSUE THREAD

**Issue by davscheno** [LucaAngioloni/fit-COVID19#2]
ho chiesto direttamente alla protezione civile, questa la risposta

https://github.com/pcm-dpc/COVID-19/issues/294#issuecomment-601598942

spero di essere di aiuto.

**Comment by valemercurii** [comment]
Ci tengo solo a precisare che io sono un utente come un altro, non della Protezione Civile.

**Comment by davscheno** [comment]
> Ci tengo solo a precisare che io sono un utente come un altro, non della Protezione Civile.

grazie per la precisazione

**Comment by LucaAngioloni** [comment]
Grazie mille per l'interesse. 

Quello che io voglio tracciare e prevedere è l'andamento dei nuovi "contagi" e non dei nuovi "attualmente positivi".

Per questo calcolo "tot oggi" - "tot ieri".

**Comment by davscheno** [comment]
giusto ho verificato e mi sono convinto, buon lavoro

**Comment by LucaAngioloni** [comment]
Grazie ancora per l'interesse.

Effettivamente l'argomento è abbastanza confuso ed infatti inizialmente ci sono cascato anche io, se non fosse che grazie alla issue #1 ci ho riflettuto e ho compreso il significato.
