### ISSUE TITLE
Predizione su attualmente positivi

### ISSUE THREAD

**Issue by MorenoLaQuatra** [LucaAngioloni/fit-COVID19#3]
Ciao Luca,

Volevo innanzitutto farti i complimenti per l'**ottimo lavoro**. Volevo chiederti come mai non è stata implementato il fitting della gaussiana sulla curva degli `attualmente positivi`. Ho provato a farlo e ottengo qualcosa di simile a questo:

![Attualmente Positivi](https://user-images.githubusercontent.com/10062811/78438795-961ead00-7677-11ea-812c-00a7945050de.png)

Ho dovuto rimuovere il `bounds` e `p0` iniziali della funzione `curve_fit`, pensi possa essere ugualmente accurato?

**Comment by LucaAngioloni** [comment]
Ciao @MorenoLaQuatra e grazie dell'interesse.

Le predizioni sulla curva degli attualmente positivi non l'avevo considerata perché non gli attribuivo troppo valore e non ero sicuro che seguisse un modello "gaussiano".

In ogni caso quello che hai fatto è corretto. Infatti ho provato ad implementarlo anche io (lo trovi commentato in fondo al file dopo l'ultimo commit).

I bounds che avevo dato all'ottimizzatore sono abbastanza restrittivi e per questa curva non sono sufficienti. Invece che rimuovere completamente i bounds, magari puoi semplicemente allargarli un po e partire con un p0 un po' più grande:

```
p0=[50000, 0.5, 1]
bounds=([10000, 0, -100], [10000000, 30, 100])
```

forse questi già vanno bene.
