### ISSUE TITLE
Aggiungere media a 3 e 7 giorni

### ISSUE THREAD

**Issue by AlessandroSpallina** [LucaAngioloni/fit-COVID19#4]
Come da titolo, si potrebbe aggiungere la possibilità di generare i grafici con media a 3 e a 7 giorni

**Comment by LucaAngioloni** [comment]
Ciao @AlessandroSpallina grazie per l'interesse.

Cosa intendi di preciso? Aggiungere al grafico con dati reali e previsione anche un plot con i dati mediati a 3-7 gg? Se si ovviamente è possibile.

In questi giorni sono un po' impegnato e non ho tempo di lavorarci e aggiungerlo. 
Se hai voglia e tempo puoi provare a farlo. Eventualmente poi posso accettare una tua Pull request.

Grazie ancora e saluti.

**Comment by LucaAngioloni** [comment]
Ciao @AlessandroSpallina, ho aggiunto la possibilità di plottare la moving average dei dati reali attraverso il parametro `--avg`, specificando la finestra di giorni ad esempio 3 o 7 come da te suggerito.

Saluti.
